# Generated by Django 4.2 on 2023-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name of the user')),
                ('phn_num', models.CharField(max_length=10, verbose_name='phone_number of the user')),
                ('adr', models.CharField(max_length=200, verbose_name='address of the user')),
                ('mem_count', models.CharField(max_length=5, verbose_name='number of family members')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
